sudo: required
services:
    - docker

before_install:
    - docker build -t dusanilic09/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run dusanilic09/react-test npm test -- --coverage

after_success:
    - docker build -t dusanilic09/multi-client ./client
    - docker build -t dusanilic09/multi-nginx ./nginx
    - docker build -t dusanilic09/multi-server ./server
    - docker build -t dusanilic09/multi-worker ./worker

#### Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

#### Push docker images
    - docker push dusanilic09/multi-client
    - docker push dusanilic09/multi-nginx
    - docker push dusanilic09/multi-server
    - docker push dusanilic09/multi-worker